<?php
session_start();
include 'includes/config1.php'; // Adjust as per your setup

// Retrieve customer details
$username = $_SESSION['admin'];
$query = "SELECT idnumber, fname, lname, email, phone, address FROM customer WHERE fname = :fname";
$stmt = $dbh->prepare($query);
$stmt->bindParam(':fname', $username);
$stmt->execute();
$user = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$user) {
    $_SESSION['error'] = "User information not found.";
    header('Location: products.php ');
    exit;
}

// Validate and retrieve transaction code
$mpesa_code = isset($_POST['mpesa_code']) ? $_POST['mpesa_code'] : '';
if (empty($mpesa_code) || strlen($mpesa_code) > 10 || !preg_match('/^[a-zA-Z0-9]{1,10}$/', $mpesa_code)) {
    $_SESSION['error'] = "Invalid M-Pesa code. Please enter a 10-character alphanumeric code.";
    header('Location: products.php ');
    exit;
}

// Calculate total price
$totalPrice = 0;
foreach ($_SESSION['cart'] as $product) {
    $totalPrice += $product['price'] * $product['quantity'];
}

// Insert order header
$query = "INSERT INTO orders (idnumber, fname, lname, email, phone, address, totalamount, transactioncode, payment_status, date_paid) 
          VALUES (:idnumber, :fname, :lname, :email, :phone, :address, :totalamount, :transactioncode, 0, NOW())";
$stmt = $dbh->prepare($query);
$stmt->bindValue(':idnumber', $user['idnumber']);
$stmt->bindValue(':fname', $user['fname']);
$stmt->bindValue(':lname', $user['lname']);
$stmt->bindValue(':email', $user['email']);
$stmt->bindValue(':phone', $user['phone']);
$stmt->bindValue(':address', $user['address']);
$stmt->bindValue(':totalamount', $totalPrice);
$stmt->bindValue(':transactioncode', $mpesa_code);

if (!$stmt->execute()) {
    $_SESSION['error'] = "Failed to place order. Please try again.";
    header('Location: products.php ');
    exit;
}

// Retrieve the order_id generated by the database
$order_id = $dbh->lastInsertId();

// Insert each product into order_items table and update stock
foreach ($_SESSION['cart'] as $product_id => $product) {
    $productName = $product['product_name'];
    $price = $product['price'];
    $quantity = $product['quantity'];
    $total = $price * $quantity;

    // Insert into order_items table
    $query = "INSERT INTO order_items (order_id, product_name, price, quantity, total) 
              VALUES (:order_id, :product_name, :price, :quantity, :total)";
    $stmt = $dbh->prepare($query);
    $stmt->bindValue(':order_id', $order_id);
    $stmt->bindValue(':product_name', $productName);
    $stmt->bindValue(':price', $price);
    $stmt->bindValue(':quantity', $quantity);
    $stmt->bindValue(':total', $total);

    if (!$stmt->execute()) {
        $_SESSION['error'] = "Failed to place order for product: $productName. Please try again.";
        header('Location: products.php ');
        exit;
    }

    // Update stock for each product
    $update_query = "UPDATE products SET stock = stock - :quantity WHERE product_id = :product_id";
    $update_stmt = $dbh->prepare($update_query);
    $update_stmt->bindParam(':quantity', $quantity);
    $update_stmt->bindParam(':product_id', $product_id);

    if (!$update_stmt->execute()) {
        $_SESSION['error'] = "Failed to update stock for product: $productName. Please try again.";
        header('Location: products.php ');
        exit;
    }
}

// Clear the cart after successful order placement
$_SESSION['cart'] = [];
$_SESSION['success'] = "Order placed successfully.";
header('Location: products.php ');
exit;
?>
